/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.persona;

import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PersonaFrm extends javax.swing.JPanel {

    /**
     * Creates new form PersonaFrm
     */
    public PersonaFrm() {
        initComponents();
    }

    public JRadioButton getBtnrFemenino() {
        return btnrFemenino;
    }

    public JRadioButton getBtnrMasculino() {
        return btnrMasculino;
    }

    public JLabel getLblErrorApellido() {
        return lblErrorApellido;
    }

    public JLabel getLblErrorCedula() {
        return lblErrorCedula;
    }

    public JLabel getLblErrorFechaNac() {
        return lblErrorFechaNac;
    }

    public JLabel getLblErrorNombre() {
        return lblErrorNombre;
    }

    public JLabel getLblErrorSexo() {
        return lblErrorSexo;
    }

    public JLabel getLblErrorSueldo() {
        return lblErrorSueldo;
    }

    public JLabel getLblErrorTelefono() {
        return lblErrorTelefono;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JTextField getTxtDia() {
        return txtDia;
    }

    public JTextField getTxtMes() {
        return txtMes;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtSueldo() {
        return txtSueldo;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblErrorFechaNac = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        btnrMasculino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnrFemenino = new javax.swing.JRadioButton();
        lblErrorCedula = new javax.swing.JLabel();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        lblErrorTelefono = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblErrorSueldo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblErrorSexo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(280, 380));
        setPreferredSize(new java.awt.Dimension(280, 380));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha nacimiento:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 30));

        txtDia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDia.setForeground(new java.awt.Color(51, 51, 51));
        add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 25, 30));

        txtMes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMes.setForeground(new java.awt.Color(51, 51, 51));
        add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 25, 30));

        txtAnio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(51, 51, 51));
        add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 50, 30));

        txtCedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(51, 51, 51));
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 180, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cédula:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        lblErrorFechaNac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorFechaNac.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorFechaNac.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErrorFechaNac.setText("Ingrese una fecha correcta. (dd/mm/aaaa)");
        add(lblErrorFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 240, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 30));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellido:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        txtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(51, 51, 51));
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 180, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sueldo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 30));

        txtSueldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(51, 51, 51));
        add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 30));

        btnrMasculino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnrMasculino.setText("Masculino");
        btnrMasculino.setOpaque(false);
        add(btnrMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Sexo:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 30));

        btnrFemenino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnrFemenino.setText("Femenino");
        btnrFemenino.setOpaque(false);
        add(btnrFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        lblErrorCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorCedula.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorCedula.setText("Ingrese una cédula correcta.");
        add(lblErrorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 20));

        lblErrorNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorNombre.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorNombre.setText("Sólo debe ingresar letras.");
        add(lblErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, 20));

        lblErrorApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorApellido.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorApellido.setText("Sólo debe ingresar letras.");
        add(lblErrorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 20));

        lblErrorTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorTelefono.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorTelefono.setText("Ingrese un teléfono correcto.");
        add(lblErrorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("/");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 260, 15, 30));

        lblErrorSueldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorSueldo.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorSueldo.setText("Sólo debe ingresar números.");
        add(lblErrorSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("/");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 260, 15, 30));

        lblErrorSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorSexo.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorSexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorSexo.setText("Debe seleccionar un sexo.");
        add(lblErrorSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 355, 190, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnrFemenino;
    private javax.swing.JRadioButton btnrMasculino;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorCedula;
    private javax.swing.JLabel lblErrorFechaNac;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorSexo;
    private javax.swing.JLabel lblErrorSueldo;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
