package vista.usuario;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class UsuarioFrm extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioFrm
     */
    public UsuarioFrm() {
        initComponents();
    }

    public JButton getBtnSelecionar() {
        return btnSelecionar;
    }

    public JLabel getLblErrorFoto() {
        return lblErrorFoto;
    }

    public JLabel getLblErrorPass() {
        return lblErrorPass;
    }

    public JLabel getLblErrorUsuario() {
        return lblErrorUsuario;
    }

    public JLabel getLblFoto() {
        return lblFoto;
    }

    public JPasswordField getTxtPass() {
        return txtPass;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblErrorUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblErrorPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnSelecionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblErrorFoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(280, 370));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        lblFoto.setMaximumSize(new java.awt.Dimension(200, 200));
        lblFoto.setMinimumSize(new java.awt.Dimension(200, 200));
        lblFoto.setPreferredSize(new java.awt.Dimension(200, 200));
        add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 200));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Usuario:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 76, 30));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 10, 180, 30));

        lblErrorUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorUsuario.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorUsuario.setText("Solo puede ingresar letras.");
        add(lblErrorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 40, 178, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contraseña:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, 30));

        lblErrorPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorPass.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorPass.setText("Contraseña muy corta.");
        add(lblErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 90, 180, 20));
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 60, 180, 30));

        btnSelecionar.setBackground(new java.awt.Color(66, 88, 110));
        btnSelecionar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSelecionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionar.setText("Seleccionar");
        btnSelecionar.setBorder(null);
        btnSelecionar.setBorderPainted(false);
        btnSelecionar.setContentAreaFilled(false);
        btnSelecionar.setFocusPainted(false);
        btnSelecionar.setOpaque(true);
        add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 110, 90, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Eleguir foto:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        lblErrorFoto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorFoto.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorFoto.setText("Seleccione una foto.");
        add(lblErrorFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 140, 175, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblErrorFoto;
    private javax.swing.JLabel lblErrorPass;
    private javax.swing.JLabel lblErrorUsuario;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
