package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PersonaFrmUI extends javax.swing.JFrame {

    //Esto lo uso para mover la ventana  
    private int mouseX; 
    private int mouseY;
    
    public PersonaFrmUI() {
        initComponents();
    }

    public JLabel getLblErrorApellido() {
        return lblErrorApellido;
    }

    public JLabel getLblErrorCedula() {
        return lblErrorCedula;
    }

    public JLabel getLblErrorFechaNac() {
        return lblErrorFechaNac;
    }

    public JLabel getLblErrorNombre() {
        return lblErrorNombre;
    }

    public JLabel getLblErrorSueldo() {
        return lblErrorSueldo;
    }

    public JLabel getLblErrorTelefono() {
        return lblErrorTelefono;
    }

    public JLabel getLblTituloVtn() {
        return lblTituloVtn;
    }

    public JPanel getPnlPrincipal() {
        return pnlPrincipal;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JTextField getTxtDia() {
        return txtDia;
    }

    public JTextField getTxtMes() {
        return txtMes;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtSueldo() {
        return txtSueldo;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public ButtonGroup getBtngSexo() {
        return btngSexo;
    }

    public JRadioButton getBtnrFemenino() {
        return btnrFemenino;
    }

    public JRadioButton getBtnrMasculino() {
        return btnrMasculino;
    }

    public JPanel getPnlFondo() {
        return pnlFondo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSexo = new javax.swing.ButtonGroup();
        pnlFondo = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblTituloVtn = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblErrorFechaNac = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        btnrMasculino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnrFemenino = new javax.swing.JRadioButton();
        lblErrorCedula = new javax.swing.JLabel();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        lblErrorTelefono = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblErrorSueldo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(302, 402));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 131, 215), 3));
        pnlFondo.setMinimumSize(new java.awt.Dimension(302, 402));
        pnlFondo.setPreferredSize(new java.awt.Dimension(302, 402));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(27, 49, 71));
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTituloVtn.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloVtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloVtn.setText("Registro de persona");
        pnlHeader.add(lblTituloVtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 30));

        pnlFondo.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 300, 30));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(66, 88, 110));
        jLabel1.setForeground(new java.awt.Color(66, 88, 110));
        jLabel1.setOpaque(true);
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, 280, 5));

        btnCancelar.setBackground(new java.awt.Color(66, 88, 110));
        btnCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setOpaque(true);
        pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 90, 30));

        btnGuardar.setBackground(new java.awt.Color(66, 88, 110));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setOpaque(true);
        pnlPrincipal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha nacimiento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 130, 30));

        txtDia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDia.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 25, 30));

        txtMes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMes.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 25, 30));

        txtAnio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 50, 30));

        txtCedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cédula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 30));

        lblErrorFechaNac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorFechaNac.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErrorFechaNac.setText("Ingrese una fecha correcta. (dd/mm/aaaa)");
        jPanel1.add(lblErrorFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 70, 30));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 70, 30));

        txtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 190, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 70, 30));

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 190, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sueldo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 30));

        txtSueldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 190, 30));

        btngSexo.add(btnrMasculino);
        btnrMasculino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnrMasculino.setText("Masculino");
        btnrMasculino.setOpaque(false);
        jPanel1.add(btnrMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Sexo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 70, 30));

        btngSexo.add(btnrFemenino);
        btnrFemenino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnrFemenino.setText("Femenino");
        btnrFemenino.setOpaque(false);
        jPanel1.add(btnrFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        lblErrorCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorCedula.setText("Ingrese una cédula correcta.");
        jPanel1.add(lblErrorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 20));

        lblErrorNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorNombre.setText("Sólo debe ingresar letras.");
        jPanel1.add(lblErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 190, 20));

        lblErrorApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorApellido.setText("Sólo debe ingresar letras.");
        jPanel1.add(lblErrorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 200, 20));

        lblErrorTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorTelefono.setText("Ingrese un teléfono correcto.");
        jPanel1.add(lblErrorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 190, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("/");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 260, 15, 30));

        lblErrorSueldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblErrorSueldo.setText("Sólo debe ingresar números.");
        jPanel1.add(lblErrorSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 190, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("/");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 260, 15, 30));

        jScrollPane1.setViewportView(jPanel1);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 310));

        pnlFondo.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 31, 300, 370));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 402));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        //Al tener sostenido el click se captura las posiciones
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Cambiamos la posicion del frame pasandole una posicion
        //Restamos la posicion actual menos la posicion general
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        //Al presionar el mause en el panel se cantura las posiciones
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup btngSexo;
    private javax.swing.JRadioButton btnrFemenino;
    private javax.swing.JRadioButton btnrMasculino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorCedula;
    private javax.swing.JLabel lblErrorFechaNac;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorSueldo;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblTituloVtn;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
